---
displayName: Quarkus Tools
description: Quarkus Tools with GraalVM and Maven 3.6.0
tags: ["Java", "Quarkus", "GraalVM", "Maven", "ubi8"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-quarkus.svg?sanitize=true
globalMemoryLimit: 2674Mi
