---
displayName: Java Vert.x
description: Java stack with OpenJDK 8, Maven 3.6.2 and Vert.x demo application
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "Vertx"]
icon: /images/type-vertx.svg
globalMemoryLimit: 2674Mi
