---
displayName: Java Maven
description: Java stack with OpenJDK 8, Maven 3.6.2 and Vert.x demo application
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "Vert.x"]
icon: /images/type-java.svg
globalMemoryLimit: 2674Mi
