---
displayName: Java EAP Thorntail
description: Quickstart to expose a REST Greeting endpoint using Thorntail with EAP 7.3, OpenJDK 11 and Maven 3.5
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Thorntail"]
icon: /images/type-thorntail.svg
globalMemoryLimit: 2674Mi
