---
displayName: Apache Camel K
description: Tooling to develop Integration projects with Apache Camel K
tags: ["Apache Camel K", "Red Hat Fuse", "Integration"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-fuse.svg?sanitize=true
globalMemoryLimit: 2850Mi
