---
displayName: Java Gradle
description: Java Stack with OpenJDK 11 and Gradle 6.1
tags: ["Java", "GraalVM", "Gradle", "ubi8"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-devfile-registry/images/type-gradle.svg?sanitize=true
globalMemoryLimit: 2674Mi
