---
displayName: ".NET"
description: .NET stack with .NET Core SDK 3.1.103, Runtime, C# Language Support and Debugger
tags: ["UBI8", ".NET", "C#", ".NET SDK", ".NET Runtime", "Netcoredbg", "Omnisharp"]
icon: /images/type-dotnet.svg
globalMemoryLimit: 2198Mi
